/// The document formats Child Assist accepts. Each one can be opened in the device's own viewer
/// app where one is installed; TXT can also be read inside the app.
enum DocumentType {
  pdf('PDF', 'application/pdf'),
  doc('DOC', 'application/msword'),
  docx('DOCX', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'),
  txt('TXT', 'text/plain');

  const DocumentType(this.label, this.mimeType);

  final String label;

  /// The standard MIME type, used when the platform does not report one.
  final String mimeType;

  /// Lower-case extension without the dot, e.g. "pdf".
  String get extension => name;

  /// The type for a label such as "PDF" (any case), or null.
  static DocumentType? fromLabel(String? label) {
    final wanted = label?.toLowerCase();
    for (final type in values) {
      if (type.extension == wanted) return type;
    }
    return null;
  }

  /// The type of [fileName] by its extension, falling back to [mimeType]. Null if unsupported.
  static DocumentType? detect(String fileName, {String? mimeType}) {
    final dot = fileName.lastIndexOf('.');
    if (dot >= 0 && dot < fileName.length - 1) {
      final ext = fileName.substring(dot + 1).toLowerCase();
      for (final type in values) {
        if (type.extension == ext) return type;
      }
    }
    final mime = mimeType?.toLowerCase();
    for (final type in values) {
      if (type.mimeType == mime) return type;
    }
    return null;
  }
}

/// A document the user picked from the device, described by metadata only. The file itself
/// stays where it is on the device; Child Assist keeps a [reference] to it and reads or opens
/// it only when the user asks.
class DocumentItem {
  const DocumentItem({
    required this.id,
    required this.name,
    required this.type,
    required this.reference,
    required this.addedAt,
    this.mimeType,
    this.size,
    this.modifiedAt,
    this.folderId,
    this.folderName,
  });

  /// Generated by Child Assist when the document is added (or, for a document in a connected
  /// folder, derived from its private reference). Says nothing about the file.
  final String id;

  /// Set for a document listed from a folder the user connected (rather than picked on its own).
  /// Such documents are listed live from the folder each time and are not stored one by one.
  final String? folderId;
  final String? folderName;

  bool get inFolder => folderId != null;

  /// File name as the platform reports it, e.g. "school_notes.pdf".
  final String name;

  final DocumentType type;

  /// e.g. "application/pdf"; null when the platform does not report one.
  final String? mimeType;

  /// Size in bytes; null when the platform does not report it.
  final int? size;

  /// When the file was last changed; null when the platform does not report it.
  final DateTime? modifiedAt;

  /// When the user added the document to Child Assist.
  final DateTime addedAt;

  /// Where the platform can find the document again (an Android content URI, or a file in
  /// the app's sandbox on iOS). Private: kept in encrypted storage, never shown, logged or
  /// included in [toJson].
  final String reference;

  /// The date shown and filtered on: when the file was last changed if known, otherwise when
  /// it was added. [isModifiedDate] says which, so the UI can label it honestly.
  DateTime get date => modifiedAt ?? addedAt;
  bool get isModifiedDate => modifiedAt != null;

  DocumentItem copyWith({String? name, String? mimeType, int? size, DateTime? modifiedAt}) => DocumentItem(
        id: id,
        name: name ?? this.name,
        type: type,
        reference: reference,
        addedAt: addedAt,
        mimeType: mimeType ?? this.mimeType,
        size: size ?? this.size,
        modifiedAt: modifiedAt ?? this.modifiedAt,
        folderId: folderId,
        folderName: folderName,
      );

  /// Metadata only, for later features (e.g. the assistant listing documents). Never contains
  /// document contents, file paths or the platform reference.
  Map<String, dynamic> toJson() => {
        'id': id,
        'name': name,
        'extension': '.${type.extension}',
        'type': type.label,
        if (mimeType != null) 'mimeType': mimeType,
        if (size != null) 'size': size,
        if (modifiedAt != null) 'modifiedAt': modifiedAt!.toUtc().toIso8601String(),
        'addedAt': addedAt.toUtc().toIso8601String(),
      };

  /// Everything needed to find the document again, for the app's own encrypted storage.
  Map<String, dynamic> toStorage() => {...toJson(), 'reference': reference};

  /// Reads an entry written by [toStorage]; null if it is malformed or of an unsupported type.
  static DocumentItem? fromStorage(Map<String, dynamic> json) {
    final id = json['id'], name = json['name'], reference = json['reference'];
    final addedAt = DateTime.tryParse(json['addedAt'] as String? ?? '');
    if (id is! String || name is! String || reference is! String || addedAt == null) return null;
    final mimeType = json['mimeType'] as String?;
    final type = DocumentType.detect(name, mimeType: mimeType);
    if (type == null) return null;
    final modified = json['modifiedAt'] as String?;
    return DocumentItem(
      id: id,
      name: name,
      type: type,
      reference: reference,
      addedAt: addedAt,
      mimeType: mimeType,
      size: json['size'] as int?,
      modifiedAt: modified == null ? null : DateTime.tryParse(modified),
    );
  }
}

/// A folder the user granted Child Assist read access to in the system folder picker. Its
/// supported documents (and those in its subfolders) are listed every time Documents opens.
class DocumentFolder {
  const DocumentFolder({required this.id, required this.name, required this.reference, required this.addedAt});

  final String id;

  /// The folder's name as the platform reports it, e.g. "Documents".
  final String name;

  /// The platform's private reference (an Android tree URI). Never shown, logged or uploaded.
  final String reference;
  final DateTime addedAt;

  Map<String, dynamic> toStorage() =>
      {'id': id, 'name': name, 'reference': reference, 'addedAt': addedAt.toUtc().toIso8601String()};

  static DocumentFolder? fromStorage(Map<String, dynamic> json) {
    final id = json['id'], name = json['name'], reference = json['reference'];
    final addedAt = DateTime.tryParse(json['addedAt'] as String? ?? '');
    if (id is! String || name is! String || reference is! String || addedAt == null) return null;
    return DocumentFolder(id: id, name: name, reference: reference, addedAt: addedAt);
  }
}

/// How a connected folder looked the last time it was listed.
class FolderStatus {
  const FolderStatus({required this.folder, required this.available, this.count = 0, this.truncated = false});

  final DocumentFolder folder;

  /// False when the folder was moved or deleted, or its access was removed in Android settings.
  final bool available;

  /// Supported documents found in it.
  final int count;

  /// It held more documents than are listed.
  final bool truncated;
}

/// Everything Child Assist can show on the Documents screen for the signed-in user.
class DocumentLibrary {
  const DocumentLibrary({required this.documents, required this.folders});

  final List<DocumentItem> documents;
  final List<FolderStatus> folders;
}

/// The simple date filter on the Documents screen, applied to [DocumentItem.date].
enum DocumentDateFilter {
  all('All dates'),
  today('Today'),
  last7Days('Last 7 days'),
  last30Days('Last 30 days');

  const DocumentDateFilter(this.label);

  final String label;

  bool matches(DateTime date, DateTime now) {
    final local = date.toLocal();
    final startOfToday = DateTime(now.year, now.month, now.day);
    return switch (this) {
      all => true,
      today => !local.isBefore(startOfToday),
      last7Days => !local.isBefore(startOfToday.subtract(const Duration(days: 6))),
      last30Days => !local.isBefore(startOfToday.subtract(const Duration(days: 29))),
    };
  }
}
